apiVersion: apps/v1
kind: Deployment
metadata:
  name: myproject
  namespace: default
  labels:
    app: myproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myproject
  template:
    metadata:
      labels:
        app: myproject
    spec:
      containers:
        - name: myproject
          image: 286280921704.dkr.ecr.eu-central-1.amazonaws.com/myproject:mor01
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 5000
            protocol: TCP
          resources:
            requests:
              memory: "200Mi"
              cpu: 0.5
            limits:
              memory: "400Mi"
              cpu: 1.0
      imagePullSecrets:
      - name: regcred              
