apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myproject
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: mor.ariel01.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myproject
            port:
              name: http
