apiVersion: v1
kind: Service
metadata:
  name: myproject
  labels:
    app: myproject
spec:
  selector:
    app: myproject
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5000
  type: ClusterIP